### ISSUE TITLE
make error - aclocal-1.16: command not found

### ISSUE THREAD

**Issue by calcut** [iris-edu/ringserver#27] opened 2020-04-30 16:30 UTC
Heads up, I had trouble compiling this on a gcloud linux box
4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux

steps:
```
git clone https://github.com/iris-edu/ringserver.git
cd ringserver
make
```
Result
```
er.o  ../pcre/.libs/libpcre.a ../libmseed/libmseed.a ../mxml/libmxml.a -lpthread
cc: error: ../pcre/.libs/libpcre.a: No such file or directory
Makefile:24: recipe for target 'ringserver' failed
make[1]: *** [ringserver] Error 1
make[1]: Leaving directory '/home/username/ringserver/src'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm no expert, and this might be an easy fix, but ringserver-2018.078 did not have this issue, so I'm trying that version now

**Comment by chad-iris** [comment] 2020-04-30 17:03
Thanks @calcut.

The missing libpcre.a library is very likely due to a build failure earlier in the `make` output.  Could you post all the output from make?

**Comment by calcut** [comment] 2020-04-30 17:08
`Running configure in pcre
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for int64_t... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether ln -s works... yes
checking whether the -Werror option is usable... yes
checking for simple visibility declarations... yes
checking for ANSI C header files... (cached) yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for sys/types.h... (cached) yes
checking for sys/stat.h... (cached) yes
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking windows.h usability... no
checking windows.h presence... no
checking for windows.h... no
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking for bcopy... yes
checking for memmove... yes
checking for strerror... yes
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
checking for gzopen in -lz... no
checking bzlib.h usability... no
checking bzlib.h presence... no
checking for bzlib.h... no
checking for libbz2... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libpcre.pc
config.status: creating libpcre16.pc
config.status: creating libpcre32.pc
config.status: creating libpcreposix.pc
config.status: creating libpcrecpp.pc
config.status: creating pcre-config
config.status: creating pcre.h
config.status: creating pcre_stringpiece.h
config.status: creating pcrecpparg.h
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing script-chmod commands
config.status: executing delete-old-chartables commands

pcre-8.43 configuration summary:

    Install prefix .................. : /usr/local
    C preprocessor .................. : gcc -E
    C compiler ...................... : gcc
    C++ preprocessor ................ : g++ -E
    C++ compiler .................... : g++
    Linker .......................... : /usr/bin/ld -m elf_x86_64
    C preprocessor flags ............ : 
    C compiler flags ................ : -g -O2 -fvisibility=hidden
    C++ compiler flags .............. : -O2 -fvisibility=hidden -fvisibility-inlines-hidden
    Linker flags .................... : 
    Extra libraries ................. : 

    Build 8 bit pcre library ........ : yes
    Build 16 bit pcre library ....... : no
    Build 32 bit pcre library ....... : no
    Build C++ library ............... : no
    Enable JIT compiling support .... : no
    Enable UTF-8/16/32 support ...... : no
    Unicode properties .............. : no
    Newline char/sequence ........... : lf
    \R matches only ANYCRLF ......... : no
    EBCDIC coding ................... : no
    EBCDIC code for NL .............. : n/a
    Rebuild char tables ............. : no
    Use stack recursion ............. : yes
    POSIX mem threshold ............. : 10
    Internal link size .............. : 4
    Nested parentheses limit ........ : 250
    Match limit ..................... : 10000000
    Match limit recursion ........... : MATCH_LIMIT
    Build shared libs ............... : no
    Build static libs ............... : yes
    Use JIT in pcregrep ............. : no
    Buffer size for pcregrep ........ : 20480
    Link pcregrep with libz ......... : no
    Link pcregrep with libbz2 ....... : no
    Link pcretest with libedit ...... : no
    Link pcretest with libreadline .. : no
    Valgrind support ................ : no
    Code coverage ................... : no

Running make all in pcre
make[1]: Entering directory '/home/username/ringserver/pcre'
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/username/ringserver/pcre/missing aclocal-1.16 -I m4
/home/username/ringserver/pcre/missing: line 81: aclocal-1.16: command not found
WARNING: 'aclocal-1.16' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:1438: recipe for target 'aclocal.m4' failed
make[1]: *** [aclocal.m4] Error 127
make[1]: Leaving directory '/home/username/ringserver/pcre'
Running configure in mxml
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for ranlib... ranlib
checking for ar... ar
checking for cp... /bin/cp
checking for ldconfig... no
checking for false... /bin/false
checking for ln... /bin/ln
checking for mkdir... /bin/mkdir
checking for rm... /bin/rm
checking for inline... inline
checking for strdup... yes
checking for strlcat... no
checking for strlcpy... no
checking for snprintf... yes
checking for vasprintf... yes
checking for vsnprintf... yes
checking for long long int... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for pthread_create using -lpthreads... no
checking for pthread_create using -lpthread... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating mxml.pc
config.status: creating config.h
Running make all in mxml
make[1]: Entering directory '/home/username/ringserver/mxml'
Compiling mxml-attr.c
Compiling mxml-entity.c
Compiling mxml-file.c
Compiling mxml-get.c
Compiling mxml-index.c
Compiling mxml-node.c
Compiling mxml-search.c
Compiling mxml-set.c
Compiling mxml-private.c
Compiling mxml-string.c
Creating libmxml.a...
a - mxml-attr.o
a - mxml-entity.o
a - mxml-file.o
a - mxml-get.o
a - mxml-index.o
a - mxml-node.o
a - mxml-search.o
a - mxml-set.o
a - mxml-private.o
a - mxml-string.o
Compiling testmxml.c
Linking testmxml...
Testing library...
Stdio file test passed!
String test passed!
File descriptor test passed!
make[1]: Leaving directory '/home/username/ringserver/mxml'
Running make all in libmseed
make[1]: Entering directory '/home/username/ringserver/libmseed'
cc   -c fileutils.c -o fileutils.o
cc   -c genutils.c -o genutils.o
cc   -c gswap.c -o gswap.o
cc   -c lmplatform.c -o lmplatform.o
cc   -c lookup.c -o lookup.o
cc   -c msrutils.c -o msrutils.o
cc   -c pack.c -o pack.o
cc   -c packdata.c -o packdata.o
cc   -c traceutils.c -o traceutils.o
cc   -c tracelist.c -o tracelist.o
cc   -c parseutils.c -o parseutils.o
cc   -c unpack.c -o unpack.o
cc   -c unpackdata.c -o unpackdata.o
cc   -c selection.c -o selection.o
cc   -c logging.c -o logging.o
Building static library libmseed.a
rm -f -f libmseed.a
ar -crs libmseed.a fileutils.o genutils.o gswap.o lmplatform.o lookup.o msrutils.o pack.o packdata.o traceutils.o tracelist.o parseutils.o unpack.o unpackdata.o selection.o logging.o
make[1]: Leaving directory '/home/username/ringserver/libmseed'
Running make all in src
make[1]: Entering directory '/home/username/ringserver/src'
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o stack.o stack.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o rbtree.o rbtree.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o logging.o logging.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o clients.o clients.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o slclient.o slclient.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o dlclient.o dlclient.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o http.o http.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o dsarchive.o dsarchive.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o mseedscan.o mseedscan.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o generic.o generic.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o ring.o ring.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre    -c -o ringserver.o ringserver.c
cc -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -I../libmseed -I../mxml -I../pcre  -o ../ringserver stack.o rbtree.o logging.o clients.o slclient.o dlclient.o http.o dsarchive.o mseedscan.o generic.o ring.o ringserver.o  ../pcre/.libs/libpcre.a ../libmseed/libmseed.a ../mxml/libmxml.a -lpthread
cc: error: ../pcre/.libs/libpcre.a: No such file or directory
Makefile:24: recipe for target 'ringserver' failed
make[1]: *** [ringserver] Error 1
make[1]: Leaving directory '/home/username/ringserver/src'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by calcut** [comment] 2020-04-30 17:28
perhaps it is because of my version of aclocal?

```
~/ringserver$ aclocal --version
aclocal (GNU automake) 1.15
Copyright (C) 2014 Free Software Foundation, Inc.
```

**Comment by chad-iris** [comment] 2020-04-30 17:37
A aclocal version 1.16 may be "fix" the issue, installing the autoconf tools that include that version may work.

Did you get the tar.gz/zip or are you building from a clone of the repository?

Really, the aclocal shouldn't be needed.  Apparently, the autoconf tools think an update of the configuration is needed, based on file time stamps, when in fact no update is needed.  I believe the issue is related to (relative) file timestamps, which are not preserved in git.

**Comment by calcut** [comment] 2020-04-30 17:45
I cloned the repo...
Didn't realise tar.gz/zip was more reliable.
I've just tried from https://github.com/iris-edu/ringserver/archive/master.zip and it built fine :-)
Thanks!

**Comment by chad-iris** [comment] 2020-04-30 17:49
Hhmmm, OK.  They _should_ be pretty much the same, another part of the mystery.

Normally, I suggest using the marked releases at:
https://github.com/iris-edu/ringserver/releases

**Comment by chad-iris** [comment] 2020-04-30 17:52
For anyone finding this issue laster, you may try the following command (in the source directory) to avoid unnecessarily trying to run `aclocal`:

```
$ touch pcre/aclocal.m4 pcre/configure pcre/Makefile.am pcre/Makefile.in
```

**Comment by chad-iris** [comment] 2020-04-30 17:52
Closing for now.  Let me know if you run into more issues.

**Closed by chad-iris** 2020-04-30 17:52 UTC
